# FYI, you can validate this file here: https://config.travis-ci.com/explore
jobs:
  allow_failures:
    - os: osx
    - os: windows
  include:
    - os: linux
      language: generic
      dist: bionic
      addons:
        apt:
          update: true
      env:
        - DISPLAY=:99.0
        - TZ=UTC0
      services:
        - xvfb
    - os: osx
      language: generic
      env:
        - DISPLAY=:99.0
      services:
        - xvfb
    - os: windows
      language: shell
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install python3-pip; sudo apt-get -y install python3-setuptools; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pip3 install tensorflow; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip3 install tensorflow; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python --version 3.6.8; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export "PATH=/c/Python36:/c/Python36/Scripts:/c/Program Files/GridLAB-D/bin:/c/Program files (x86)/Graphviz2.38/bin:/c//Program Files/GridLAB-D/bin/$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ln -s /c/Python36/python /usr/bin/python3; ln -s /c/Python36/Scripts/pip /usr/bin/pip3; fi
  - python3 install.py
  - export BOTO_CONFIG=/dev/null
install:
  - sudo python3 setup.py develop || python setup.py develop
before_script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export "PATH=/c/Python36:/c/Python36/Scripts:/c/Program Files/GridLAB-D/bin:/c/Program files (x86)/Graphviz2.38/bin:$PATH"; fi
script:
  - python3 ./omf/runAllTests.py omf
  - cd omf/models
  - python3 forecastTool.py
  - python3 smartSwitching.py
  - python3 networkStructure.py